# This is a basic workflow to help you get started with Actions

name: simple_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  show_release:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@master
        with:
          branch: v3.15
          extra-repositories: http://apk.bell-sw.com/main

      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
        
      - run: ls -al /etc/apk/keys
        shell: alpine.sh {0}        
